# Generated by Django 3.0.5 on 2020-05-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isProvider',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
