# Generated by Django 3.0.5 on 2020-05-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_isprovider'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.TextField(blank=True, null=True),
        ),
    ]
