# Generated by Django 3.0.5 on 2020-06-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_meal_menu_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='recipe',
        ),
        migrations.AddField(
            model_name='meal',
            name='recipe_id',
            field=models.IntegerField(default=0),
        ),
    ]
