# Generated by Django 3.0.5 on 2020-05-21 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200519_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='deneme',
        ),
    ]
