# Generated by Django 3.0.7 on 2020-06-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200622_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='duration',
            field=models.CharField(default='', max_length=50),
        ),
    ]
