# Generated by Django 3.0.5 on 2020-05-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_recipe_deneme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='isProvider',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='user_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
