# Generated by Django 3.0.5 on 2020-06-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200530_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='nutrients',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
