# Generated by Django 3.0.5 on 2020-06-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_recipe_nutrients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='nutrients',
            field=models.TextField(default='', max_length=5000),
        ),
    ]
