# Generated by Django 3.0.5 on 2020-06-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_recipe_usdaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default='', max_length=50000),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='nutrients',
            field=models.TextField(default='', max_length=50000),
        ),
    ]
