# Generated by Django 3.0.5 on 2020-06-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20200619_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='birthday',
            field=models.CharField(default='', max_length=50),
        ),
    ]
